app_1/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import auth_login, auth_logout

urlpatterns = [

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # index dan dashboard
    url(r'^$', index, name='index'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
	url(r'^post_status', post_status, name='post-status'),

]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_1.urls as app_1
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app2-1/', include(app_1,namespace='app2-1')),
    url(r'^$', RedirectView.as_view(url="/app2-1/", permanent = "true"), name='index'),
]

app_1/models.py
from django.db import models

class User(models.Model):
    identity_number = models.CharField(max_length=20)
    name = models.CharField(max_length=200)

class Status(models.Model):
    user = models.ForeignKey(User)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Keahlian(models.Model):
    nama = models.CharField(max_length=27)
    tingkat = models.CharField(max_length=27)

    class Meta:
        ordering = ('nama',)
    
    def __str__(self): # pragma: no cover
        return self.nama + self.tingkat

class Mahasiswa(models.Model):
    npm = models.CharField(max_length=10)
    nama = models.CharField(max_length=27)
    angkatan = models.CharField(max_length=27)
    keahlian = models.ManyToManyField(Keahlian)

    class Meta:
        ordering = ('npm',)

    def __str__(self): # pragma: no cover
        return self.nama

app_1/forms.py
from django import forms


class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
   
    
    status_attrs = {
        'type': 'text',
				
        'class': 'status-form-textarea',
        'placeholder':'Apa yang anda pikirkan?...'
    }

    
    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

app_1/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.core import serializers

from .forms import Status_Form
from .models import Mahasiswa, Keahlian, User, Status
from .api_riwayat import get_matkul

response = {}
response["author"] = "Kelompok 3A"

# NOTE : untuk membantu dalam memahami tujuan dari suatu fungsi (def)
# Silahkan jelaskan menggunakan bahasa kalian masing-masing, di bagian atas
# sebelum fungsi tersebut.

# ======================================================================== #
# User Func
# Apa yang dilakukan fungsi INI? #silahkan ganti ini dengan penjelasan kalian
def index(request): # pragma: no cover
    # print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('app2-1:dashboard'))
    else:
        html = 'app_1/login.html'
        return render(request, html, response)

def dashboard(request): # pragma: no cover
    if 'user_login' in request.session:
        response['is_login'] = True
        
        username = request.session['user_login']
        kode_identitas = request.session['kode_identitas']
        
        response['user'], is_login = User.objects.get_or_create(identity_number=kode_identitas, name=username)
        my_Status= Status.objects.filter(user_id=response['user'].id)
        response['all_status'] = Status.objects.filter(user_id=response['user'].id)
        response['Status']= response['all_status'][::-1]

        if len(my_Status)== 0:
            response['last_status']='-'
        else:
            response['last_Status']=response['Status'][0]
            
        response['status_count'] = response['all_status'].count()
        response['status_form'] = Status_Form

        set_data_for_session(response,request)
        html = 'app_1/dashboard.html'
        return render(request, html, response)

    response['is_login'] = False
    html = 'app_1/login.html'
    return render(request, html, response)

def set_data_for_session(res, request): # pragma: no cover
    response['author'] = request.session['user_login']
    response['access_token'] = request.session['access_token']
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']
    response['friends'] = Mahasiswa.objects.all()
    response['matkul_list'] = get_matkul().json()

	
def post_status(request): # pragma: no cover
    form = Status_Form(request.POST or None)
    if 'user_login' in request.session and request.method == 'POST' and form.is_valid():
        response['is_login'] = True
        
        username = request.session['user_login']
        kode_identitas = request.session['kode_identitas']
        status_message = request.POST['status']
        response['user'], is_login = User.objects.get_or_create(identity_number=kode_identitas, name=username)
        new_status = Status.objects.create(description=status_message, user=response['user'])
        return HttpResponseRedirect(reverse('app2-1:dashboard'))
        
    response['is_login'] = False
    html = 'app_1/login.html'
    return render(request, html, response)

app_1/templates/app_1/dashboard.html
{% extends "app_1/layout/base2.html" %}
{% load staticfiles %}
{% load static %}
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/app_1.css' %}" />
</head>

{% block content %}
<!-- Content Here -->
<div class="pojok-kanan">
</div>
<br>
<div class="panel panel-default">
    <div class="panel-heading" style="background-color:lightsteelblue;">
        <b><p class="head"> Selamat Datang, {{ user.name }} </h2></p>
    </div>
    <div class="panel-body" style="background-color: #FFF5EE;">
		<img src="https://pixabay.com/static/img/profile_image_dummy.svg" class="img-circle" height="150" width="150" align="left"></img>
       
        <a href="#" style="text-align:left;float:up;">
            <button type="button" class="btn btn-default" id="forum-button"> <b>Lihat Forum</b> </button>
        </a>
        <b style="text-align:left" class="jumlah-status">  <img src="https://png.icons8.com/metro/540/new-post.png" width="35px" height="35px" id="img-forum"></img> {{ status_count }}</b><br>

        <a href="#" style="text-align:left;float:down;">
            <button type="button" class="btn btn-default" id="profile-button"><b>Edit Profile</b></button>
			
        </a>
		
		<h4 style="text-align:center;float:up;" class="last-status"><br> <p style="text-align:center"><i><b> " {{last_Status.description}}"</b></p></i></h4>
        
    </div>
</div>

<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active">
            <a href="#status" aria-controls="home" role="tab" data-toggle="tab"> Status </a>
        </li>
		

	   <li role="presentation">
            <a href="#profile" aria-controls="settings" role="tab" data-toggle="tab"> Profile</a>
        </li>
        <li role="presentation">
            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
        </li>
        <li role="presentation">
            <a href="#teman" aria-controls="settings" role="tab" data-toggle="tab"> Teman </a>
        </li>
    </ul>
	

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="status">
            {% include 'app_1/tabs/status.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="profile">
            <!-- Apply the same here -->
            {% include 'app_1/tabs/profile.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="riwayat">
            <!-- Apply the same here -->
            {% include 'app_1/tabs/riwayat.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="teman">
            <!-- Apply the same here -->
            {% include 'app_1/tabs/teman.html' %}
        </div>
    </div>
</div>
{% endblock %}

app_1/templates/app_1/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Tugas 2">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/app_1.css' %}" />
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }

		.foot{
		font-size:16px;
		margin-left:680px;
		}

        .Beginner{
            color: green
        }

        .Intermediate{
            color: Blue
        }

        .Advance{
            color: red
        }

        .Expert{
            color: purple
        }

        .Legend{
            color: goldenrod
        }

	
    </style>
    <title>
        {% block title %} OwO By {{author}} {% endblock %}
    </title>
</head>
<body>
<header>
     {% include "app_1/partials/header.html" %}
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    <hr>
    {% block footer %}


         <p style="text-align:center">Made with Love by &copy; Kelompok 3A</p>

    <!-- Your Footer Here -->
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app_1/templates/app_1/layout/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Tugas 2">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/app_1.css' %}" />
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }

			.objekPertama{
			margin-left:800px;
		}
		
		
		.objekKedua img{
			height:50px;
			width: 50px;
		}
		
		.objekPertama img{
			height:50px;
			width: 50px;
			
		}
		.foot{
		font-size:16px;
		margin-left:680px;
		}

        .Beginner{
            color: green
        }

        .Intermediate{
            color: Blue
        }

        .Advance{
            color: red
        }

        .Expert{
            color: purple
        }

        .Legend{
            color: goldenrod
        }

	.row{
		background-color:#ADD8E6;
		border:4px solid rgba(0,0,0,0.3);
		border-radius:8px;
	}
    </style>
    <title>
        {% block title %} OwO By {{author}} {% endblock %}
    </title>
</head>
<body>
<header>
	 {% include "app_1/partials/header2.html" %}
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    <hr>
    {% block footer %}


         <p style="text-align:center">Made with Love by &copy; Kelompok 3A</p>

    <!-- Your Footer Here -->
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app_1/templates/app_1/login.html
{% extends "app_1/layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1 > </h1><img src="https://upload.wikimedia.org/wikipedia/id/thumb/9/95/Makara_UI.png/937px-Makara_UI.png" width="150px" height="150px" class="gambarku">
                <p class="text-info"><br> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'app2-1:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
					<label for="username"> Password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary" value="Login" id="login-but">
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_1/templates/app_1/partials/header.html
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Login untuk melanjutkan...</a>
    </div>
    
  </div>
</nav>

app_1/templates/app_1/partials/header2.html
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	 
  
    
	 <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
		<li class="objekKedua"><a href="{% url 'app2-1:dashboard'%}" ><img src="https://image.flaticon.com/icons/png/512/25/25694.png" > </img></a></li>
        <li class="objekPertama" ><a href="{% url 'app2-1:auth_logout' %}">Logout <img src="https://image.flaticon.com/icons/png/128/56/56805.png" > </img></a></li>
      </ul>
    </div><!--/.nav-collapse -->
    
  </div>
</nav>

app_1/templates/app_1/tabs/profile.html
<div class="container2">
	 <div class="panel panel-info">
    <div class="panel-heading">
        <h2> Profile</h2>
    </div>
	<p class="prof">
		Nama :		-
	<br><br>
	Role :		{{role}}
	<br><br>
	NPM  :		{{kode_identitas}}
	<br><br>
	Keahlian : -
	<br><br>
	Email: -
	<br><br>
	Profil Linkedin: - 
	</p>
    </div>
	



   

</div>

app_1/templates/app_1/tabs/riwayat.html
{% block content %}
<div class="panel panel-info">
  <div class="panel-heading">
    	<h2> History </h2>
  </div>
	<div class="panel-body">
        <table class="table">
            <thead>
	            <th> No </th>
	            <th> Nama Mata Kuliah </th>
	            <th> Kode Kelas </th>
	            <th> Nilai </th>
	            <th> Term </th>
	            </thead>
            <tbody>
            {% for matkul in matkul_list %}
            <tr>
                <td> {{ forloop.counter }}</td>
                <td> {{ matkul.kelas.nm_mk_cl.nm_mk }}</td>
                <td> {{ matkul.kelas.kd_kls }}</td>
                <td> {{ matkul.nilai }}</td>
                <td> {{ matkul.term }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app_1/templates/app_1/tabs/status.html
<div class="container2">
	 <div class="panel panel-info">
    <div class="panel-heading">
        <h2> Post Status</h2>
    </div>
		{% if role  == "mahasiswa" %}
        <div class="panel-body">
            <section name="form">
                <form id="form" method="POST" action="{% url 'app2-1:post-status' %}">
                    {% csrf_token %}
                    {{ status_form }}
					<br>
					<div class="but">
						<input id="submit" type="submit" class="post-button" value="Post">
					</div>
                </form>
            </section>
        </div>
		
		{% else %}
		<p></p>
		
		{% endif %}
    </div>
	



    {% for status in Status %}
    <div class="panel panel-default">
        <div class="panel-heading" >
		<img src="https://pixabay.com/static/img/profile_image_dummy.svg" class="img-circle" height="50" width="50" align="left"></img>
            <h3> {{ user.name }} </h3>
            <h5> at {{ status.created_at }} </h5>
        </div>
        <div class="panel-body">
            <p class="status-text"> {{ status.description }} </p>
        </div>
    </div>
    {% endfor %}

</div>

app_1/templates/app_1/tabs/teman.html
<div class="panel panel-info">
    <div class="panel-heading">
        <h2> Friends </h2>
    </div>

    <div class="panel-body">
        <div style="margin:20px; padding:20px; background-color:lightsteelblue; border-radius:3px;">
            <form method="GET"  class="form-inline">
                <input type="text" class="form-control" id="parameter" onkeyup="myFunction()" name="parameter" placeholder="Search" title="Type in a parameter">
                <input type="radio" name="type" style="margin-left:20px" value="0" checked> NPM
                <input type="radio" name="type" style="margin-left:20px" value="1"> Nama
                <input type="radio" name="type" style="margin-left:20px" value="2"> Angkatan
                <input type="radio" name="type" style="margin-left:20px" value="3"> Keahlian
                <input type="radio" name="type" style="margin-left:20px" value="4"> Level
            </form>
        </div>
        <table id="friendTable" class="table">
            <thead>
            <th> NPM </th>
            <th> Nama </th>
            <th> Angkatan </th>
            <th> Keahlian </th>

            </thead>
            <tbody>
            {% for friend in friends %}
            <tr>
                <td> {{ friend.npm }}</td>
                <td> {{ friend.nama }}</td>
                <td> {{ friend.angkatan }}</td>
                <td>
                {% for keahlian in friend.keahlian.all %}
                <div class="{{ keahlian.tingkat }}">
                    {{keahlian.nama}}
                </div>
                {% endfor %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
function myFunction() {
  var input, filter, table, tr, td, i, type;
  input = document.getElementById("parameter");
  filter = input.value.toUpperCase();
  table = document.getElementById("friendTable");
  tr = table.getElementsByTagName("tr");
  console.log(tr);
  type = document.querySelector('input[name="type"]:checked').value;
  if(type<'3'){
    for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[type];
        if (td) {
            if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }
  }
  else{
    for (i = 0; i < tr.length; i++) {

        td = tr[i].getElementsByTagName("td")[3];
        if (td) {
            div = td.getElementsByTagName("div");
            for(n=0; n<div.length; n++){
                if(type==3){
                    if (div[n].innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                        break;
                    } else {
                        tr[i].style.display = "none";
                    }
                }
                else{
                    if (div[n].className.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                        break;
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    }
  }

}
</script>

</body>
</html>